name: computed
description: Straightforward, reliable, performant and testable reactive state management

repository: https://github.com/mstniy/computed.dart

version: 0.0.1

environment:
  sdk: ">=2.16.0 <3.0.0"
dependencies:
  built_collection: ^5.1.1
  meta: ^1.11.0
dev_dependencies:
  matcher: ^0.12.16
  test: ^1.24.9
