name: computed
description: Computed

publish_to: "none"
version: 0.0.0+0

environment:
  sdk: ">=2.16.0 <3.0.0"
dependencies:
  built_collection: ^5.1.1
dev_dependencies:
  matcher: ^0.12.16
  test: ^1.24.9
