name: computed
description: Straightforward, reliable, performant and testable reactive state management

repository: https://github.com/mstniy/computed.dart

version: 0.4.1

environment:
  sdk: ">=2.16.0 <4.0.0"
dependencies:
  meta: ">=1.3.0 <2.0.0"
dev_dependencies:
  built_collection: ^5.1.1
  tuple: ^2.0.2
  matcher: ^0.12.16
  test: ^1.24.9
