name: computed
description: A performant and flexible reactive programming framework for Dart

repository: https://github.com/mstniy/computed.dart

version: 0.5.0

environment:
  sdk: ">=3.2.1 <4.0.0"
dependencies:
  meta: ">=1.3.0 <2.0.0"
dev_dependencies:
  built_collection: ^5.1.1
  tuple: ^2.0.2
  matcher: ^0.12.16
  test: ^1.24.9
  lints: ^4.0.0
