name: computed_collections
description: Performant and flexible functional reactive programming for collections

repository: https://github.com/mstniy/computed.dart/tree/master/packages/computed_collections

version: 0.1.2

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  meta: ">=1.3.0 <2.0.0"
  fast_immutable_collections: "^11.0.3"
  computed: "^0.5.1"
dev_dependencies:
  lints: ^5.1.1
  matcher: ^0.12.17
  test: ^1.25.15
