name: computed_collections
description: Performant, reactive and immutable collections for Computed

repository: https://github.com/mstniy/computed.dart

version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  meta: ">=1.3.0 <2.0.0"
  fast_immutable_collections: "^10.2.4"
  computed:
    path: ../computed
dev_dependencies:
  matcher: ^0.12.16
  test: ^1.24.9
