name: computed_collections
description: Performant, reactive and immutable collections for Computed

repository: https://github.com/mstniy/computed.dart

version: 0.0.1

environment:
  sdk: ">=2.16.0 <4.0.0"
dependencies:
  meta: ">=1.3.0 <2.0.0"
  fast_immutable_collections: "^10.1.0"
  computed: "^0.4.1"
dev_dependencies:
  matcher: ^0.12.16
  test: ^1.24.9
