name: computed

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  tests:
    uses: ./.github/workflows/test_main.yml
    with:
      package: computed
    secrets: inherit
