name: computed_collections

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test:
    uses: ./.github/workflows/test_main.yml
    with:
      package: computed_collections
    secrets: inherit
