name: tests

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  computed:
    uses: ./.github/workflows/test_main.yml
    with:
      package: computed
  computed_collections:
    uses: ./.github/workflows/test_main.yml
    with:
      package: computed_collections
